### ISSUE TITLE
Access Local Web Server?

### ISSUE THREAD

**Issue by km4ack** [VA3HDL/hamdashboard#1]
Is it possible to access a local web server in one of the 12 windows? I tried 127.0.0.1:8008 as the server is running on the same machine but it doesn't show. The local server is not https.

**Comment by VA3HDL** [comment]
Hi Jason,

Yes it is possible. I just tried with a picture URL like this:
http://127.0.0.1:8080/20230805_125405.jpg

It shows perfectly on one of the 12 placeholder.

Make sure you fetch my latest version that now supports multiple (infinite) images per placeholder. You can switch them with the right mouse click.

73,
Pablo

**Comment by km4ack** [comment]
Figured it out. I was only pointing to an html page. After including the image name at the end or the URL, it pulls in perfectly. Thanks!
