### ISSUE TITLE
Image being cached in dashboard panel

### ISSUE THREAD

**Issue by midair55** [VA3HDL/hamdashboard#10]
Dave (N2MXX) dashboard had this issue and he implemented a parameter in the panel definition to resolve the caching.  I believe the change was made in v2.24

[
    "Tide Table",
    "https://wave.marineweather.net/itide/tides/png/fl_trident_pier_port_canaveral.png"
  ],

The, "png" is automatically updated periodically but a manual or automatic refresh of the dashboard does not fetch the updated image.

Chrome Version 125.0.6422.142 (Official Build) (64-bit) 

Great job!!!  Steve - N5NG

**Comment by VA3HDL** [comment]
Hi Steve,

Let me try on my dashboard. If I can reproduce myself I will fix. The fix for this is easy.

73,
Pablo, VA3HDL

**Comment by midair55** [comment]
Wonderful!   Thank you for the quick fix!
