### ISSUE TITLE
Rotate large image on right click

### ISSUE THREAD

**Issue by KF0FTU** [VA3HDL/hamdashboard#16]
Rotating through multiple images while in the large image mode would be nice. Currently, if I want to view the next image of a given tile in large image mode the sequence is as follows:

1. Double-click to return to the dashboard (all tiles reset to index 0)
2. Right-click the tile until the image desired image is visible 
3. Double-click tile to enlarge

This is not a problem until the desired image has text to determine which image is shown (timestamp data) which is too small to read in tile form.

Example of a tile's images for 3 days of forecast information:
`  [
    "NOAA FORECAST",
    "https://www.wpc.ncep.noaa.gov/NationalForecastChart/staticmaps/noaad1.png",
    "https://www.wpc.ncep.noaa.gov/NationalForecastChart/staticmaps/noaad2.png",
    "https://www.wpc.ncep.noaa.gov/NationalForecastChart/staticmaps/noaad3.png",
  ]  `

In looking at the code, I did not see an easy way to add this. It would take either looking up the URL to determine which tile array is selected or passing a value of the given `aIMG[i][aIdx[i]]` when replacing the backgroundImage to know which URL to index. 

Thank you for this great dashboard!

**Comment by VA3HDL** [comment]
It is a good feature. Let me look into this. I will let you  know once is done. Thanks. 73

**Comment by VA3HDL** [comment]
Hi Travis,

The feature you requested was added in the latest .html file. This is the only file you need to update with the github repo version.

73 de Pablo, VA3HDL
