### ISSUE TITLE
No Menu

### ISSUE THREAD

**Issue by lscalpati** [VA3HDL/hamdashboard#2]
I just cloned your repo and opened the html page in Google Chrome.  The menu is missing.  I checked developer tools and the JS is loading but there is a javascript error in the code.

Uncaught TypeError: Cannot set properties of null (setting 'textContent')
    at updateTopBar (VM136 hamdash.html:281:30)
    at VM136 hamdash.html:292:5

 topBarLeft.textContent = `${localDate} - ${localTime}`;
Uncaught Type Error: Cannot set properties of null(setting 'text content')

**Comment by VA3HDL** [comment]
I pushed an update to fix the JavaScript error your reported and the error is now resolved.

The menu is hidden you have to move the mouse closer to the top edges on both sides of the screen to make them visible. Maybe is that.

Please get the updated file and let me know if everything is good. Thanks.

**Comment by lscalpati** [comment]
installed update and now I can get to the menu.  This is a problem with overlap of the menu tabs.  I am going to close this and open another for that bug.  Thanks!
