### ISSUE TITLE
Cache prevention interfering with Hamclock BMP display

### ISSUE THREAD

**Issue by nq0m** [VA3HDL/hamdashboard#33]
So this is a rather non-ordinary setup I'm using, and while I'm pretty sure I've exhausted all the possible reasons my setup could cause this, I'm not totally sure, so I want to explain in depth.  Hamdashboard itself is hosted via Cloudflare Pages at:

https://hamdash.nq0m.com/

11 of the 12 panes work just fine.  One pane is the get_capture.bmp output from my Hamclock installation's REST API endpoint (as described in KM4ACK's YouTube video), and this is the one giving me a problem.  Since my Hamclock is running on my local network, I'm using a Cloudflare Tunnel to expose it.  I have disabled all caching and WAF rules on Cloudflare for this url:

https://hamclock-static.nq0m.com/get_capture.bmp

The first load goes fine (I assume because the code does not used the cache prevention on the first load).  Subsequent reloads fail.  In the Developer Tools console of the browser I see:

Failed to load image https://hamclock-static.nq0m.com/get_capture.bmp?_=1729439787928
Trying without caching prevention

Checking the cache prevention URL against the Hamclock server exposes why it's failing - with the ?_=##### added, the REST API actually gives a plain text "help" output for the API.  However, despite the message above about trying without the cache prevention,  on the Network tab of Developer tools, I can never actually see a request being sent for get_capture.bmp without the cache prevention query string.

I should also note that even when not using the tunnel, and accessing Hamclock directly on my private network, the exact same issue occurs.

Hopefully this gives you enough information, but I can certainly answer any questions you may have.  If we can't figure this out, I suppose I could set up Cloudflare to remove the query string, but I really think it might be worthwhile to be able to have an option to disable the cache prevention within the config.js.

**Comment by VA3HDL** [comment]
Hi,

Temporarily you can disable the caching for everything by changing this function:

    // Image cache prevention
    // Check if the image URL already include parameters, then avoid the random timestamp
    function imgURL(url) {
      if (url.includes("?")) {
        return url;
      }
      return url + "?_=" + Date.now();
    }


With this:

    // Image cache prevention
    // Check if the image URL already include parameters, then avoid the random timestamp
    function imgURL(url) {
      if (url.includes("?")) {
        return url;
      }
      return url;
    }


This is removes the cache prevention altogether.

I will investigate a better alternative to add this in the configuration file.

Thanks.

**Comment by midair55** [comment]
I create a bmp file using the, "get_capture.bmp" command via crontab and configured the dashboard to point to the bmp file.  There is no caching issue.  Granted there is a slight chance of a race condition where the panel is refreshing at the same time the bmp is being created but I haven't witnessed it.

**Comment by irresisti** [comment]
Hi, My setup also experiences this problem. It never updates and throws the caching prevention error.

**Comment by VA3HDL** [comment]
> Hi, My setup also experiences this problem. It never updates and throws the caching prevention error.

What looks like? This?
![image](https://github.com/user-attachments/assets/03d577c8-0e70-4038-b62c-3a9e3c0a003d)
