### ISSUE TITLE
Website URL

### ISSUE THREAD

**Issue by Stef198** [VA3HDL/hamdashboard#34]
Hi, I'm trying to add URL from website like :

Hydro-Quebec abd Google maps on live but it keeps saying the websites do not accept connection.

Is there something I need to do different?,  When I remove the iframe, it says Failed to load image...     I want websites  live.

**Comment by Stef198** [comment]
Hi again,     

Not sure if you can look at those URL I would like to be able to see and expend is required:

1. https://radar.weather.gov/?settings=v1_eyJhZ2VuZGEiOnsiaWQiOm51bGwsImNlbnRlciI6Wy03OC43NDEsNDEuNjE1XSwibG9jYXRpb24iOm51bGwsInpvb20iOjQuOTA0NjkzMzM4MjE0NTMxfSwiYW5pbWF0aW5nIjpmYWxzZSwiYmFzZSI6InN0YW5kYXJkIiwiYXJ0Y2MiOmZhbHNlLCJjb3VudHkiOmZhbHNlLCJjd2EiOmZhbHNlLCJyZmMiOmZhbHNlLCJzdGF0ZSI6ZmFsc2UsIm1lbnUiOnRydWUsInNob3J0RnVzZWRPbmx5IjpmYWxzZSwib3BhY2l0eSI6eyJhbGVydHMiOjAuOCwibG9jYWwiOjAuNiwibG9jYWxTdGF0aW9ucyI6MC44LCJuYXRpb25hbCI6MC42fX0%3D

2. https://www.gdacs.org/#:~:text=GDACS%20is%20a%20cooperation%20framework%20between%20the%20United

3. https://rsoe-edis.org/eventMap#:~:text=Explore%20the%20latest%20global%20events%20and%20disasters%20on

4. https://www.meteoblue.com/fr/meteo/cartes/blainville_canada_5903510#coords=6.09/46.431/-74.287&map=radar~radarMapUSA~none~none~none

5. https://infopannes.solutions.hydroquebec.com/info-pannes/pannes/pannes-en-cours

6. https://zoom.earth/maps/satellite/#view=44.8796,-75.552,7z

7. https://www.ventusky.com/fr/blainville

8. https://www.quebec511.info/fr/Carte/Default.aspx

9. https://tornado.live/wx/KTBW-FF-W-0015/

10. https://www.windy.com/45.679/-73.876?45.242,-73.876,8,m:eVnad5W

11. https://vigilance.geo.msp.gouv.qc.ca/carte

12. Winlink

It's when I monitor for CanWarn.

**Comment by VA3HDL** [comment]
Hi,

You can have live websites on the tiles or via the menus on the sides. I both cases the live websites load via iframes.

Not every website works inside an iframe and this is a website owner prerogative to allow it or not. More details are on the main README.md file.

Sites will be expanded when the sites are linked and loaded via the menus.

Sites will NOT be expanded when loaded inside the tiles.
