### ISSUE TITLE
hamdash.html error

### ISSUE THREAD

**Issue by sconnaug** [VA3HDL/hamdashboard#35]
When I open the current version of hamdash.html that I downloaded with config.js and wheelzoom.js I get the site below. All files are in the same folder like the previous version. I had no issues with the old version.

What am I missing?

![error 2024-11-04 172431](https://github.com/user-attachments/assets/8c50eb49-a5f8-4c7f-884c-5d7920cecae4)

**Comment by VA3HDL** [comment]
It seems you saved the github page instead of downloading the files.
![image](https://github.com/user-attachments/assets/7da38982-2d20-4a1c-9c82-0de06c0f78ee)
Click on Code (green button) then  Download ZIP

**Comment by sconnaug** [comment]
That's what I missed. Thanks
