### ISSUE TITLE
Quad View

### ISSUE THREAD

**Issue by NullVibes** [VA3HDL/hamdashboard#36]
Request an option for reducing the number of iframes displayed.  Quad view?

I've recently returned from a deployment into the TN/NC disaster area caused by Hurricane Helene, and used your Ham Dashboard in our operations center, connected to a video projector.  We found that displaying 12 windows was too much.  We didn't have 12 datasources that we wanted to track on this display, and those windows that were important to us weren't large enough to be useful even when projected onto a large screen.  A simpler 2x2 quad-view would have been great.  I've been periodically monkeying with the code to accomplish this, but I figured you could probably accomplish this feature much faster than me.

Thank you for your work on this project!  It's terrific.

**Comment by VA3HDL** [comment]
Hi,

This has been requested multiple times already and you are the first one that provided a good reason to do it.
Let me start working on this and I will let you know when it will be available.

I would love to receive some photos (if you have) of your deployment showing the dashboard usage in the emergency.

My email is good in QRZ.com

Thanks.

**Comment by NullVibes** [comment]
Thank you!  I'll see if I can dig up a picture, however, we had a (fairly) strict No Photography policy in the TOC.  Maybe we'll get lucky though.  Bless you for your work!

**Comment by VA3HDL** [comment]
A new release is now available including this requested functionality.
Please check and let me know if you encounter any issues.
Thanks.
