### ISSUE TITLE
5x3 configuration - Some panels on bottom row are not updating

### ISSUE THREAD

**Issue by midair55** [VA3HDL/hamdashboard#37]
https://qsl.net/n5ng/  is configured for 5 columns x 3 rows.  Only panels 1 and 2 of the last row are updating.  All panels on the bottom row have more than one image or iframe URL defined.   The "Traffic" panel is defined with only images.  Attempts to manually rotate them via right-click does not rotate.

The config.js may be viewed at: https://qsl.net/n5ng/config.txt

**Comment by VA3HDL** [comment]
Yeah, I'm able to confirm the issue. Let me try to fix it.

**Comment by midair55** [comment]
Pablo - Thanks for the quick response!!

I also did not get the new release pop-up notice yesterday when the latest
html was posted.

**Comment by VA3HDL** [comment]
Hi Steve,

I found the issue and fixed the code. Please download the updated hamdash.html file from the repo and let me know if you encounter any new issues.

Thanks

**Comment by midair55** [comment]
Wilco.  Thanks!
