### ISSUE TITLE
Menu Items overlap

### ISSUE THREAD

**Issue by lscalpati** [VA3HDL/hamdashboard#4]
Menu items overlap on both left and right menus.

Also:
- On left menus they also are cutoff on the left buy about 1/3 when expanded.  When not activated, I can not see the collapsed tabs on the edge

- On right menus they are too far to the left with a large gap between the right end of the tab and the right side of the screen.

**Comment by VA3HDL** [comment]
Please attach screenshot. I'm using Chrome and Firefox for testing and in both it is working perfectly.

**Comment by lscalpati** [comment]
using Chrome on ubuntu

![Screenshot_2024-05-27_09-37-37](https://github.com/VA3HDL/hamdashboard/assets/19877088/f70be1e3-8e2d-4a11-a8b9-a1a1d599ef4f)
![Screenshot_2024-05-27_09-34-34](https://github.com/VA3HDL/hamdashboard/assets/19877088/e564a438-dcac-47bc-9bbd-0c496901b180)

**Comment by VA3HDL** [comment]
Hi Lou, after checking with various browsers on several computers I found only one case similar to yours using an old version of Chromium 
![image](https://github.com/VA3HDL/hamdashboard/assets/96899520/d93c2b67-e13f-48b8-be2d-ee8fc714f7c0)

Once I updgraded to its latest:
![image](https://github.com/VA3HDL/hamdashboard/assets/96899520/e766b81e-e13a-451a-b8b7-dab1b1b90886)

The dashboard menu options show as they should.

In your case the browser is asking you to upgrade:
![image](https://github.com/VA3HDL/hamdashboard/assets/96899520/9d30f659-90c9-4886-a949-7d0cd62b99cd)

Please upgrade and let us know if that fixes your issue with the menues.
Thanks

**Comment by lscalpati** [comment]
That worked - thanks
