### ISSUE TITLE
config.js file

### ISSUE THREAD

**Issue by ND5CL** [VA3HDL/hamdashboard#40]
i get this error. Erorr detected on config.js file

The number of tile sources (16 in aIMG) and the tile delay (16 in tile delay) arrays should  match the number of items each one contains and the number of tiles used on the layout specified (12)

what do i need to look for to fix this

**Comment by VA3HDL** [comment]
As explained on the instructions here:
https://github.com/VA3HDL/hamdashboard?tab=readme-ov-file#20241113-changelog

You should add these lines to your config.js file with the appropriate number of columns and rows you desire. 

  // Grid layout for 16 tiles
  var layout_cols = 4;
  var layout_rows = 4;

**Comment by ND5CL** [comment]
Ok thank youSent from my iPhoneHank Watkins On Nov 26, 2024, at 4:00 PM, Pablo ***@***.***> wrote:﻿
As explained on the instructions here:
https://github.com/VA3HDL/hamdashboard?tab=readme-ov-file#20241113-changelog
You should add these lines to your config.js file with the appropriate number of columns and rows you desire.
// Grid layout for 16 tiles
var layout_cols = 4;
var layout_rows = 4;
