### ISSUE TITLE
Unable to scroll on web pages accessed by menu

### ISSUE THREAD

**Issue by lscalpati** [VA3HDL/hamdashboard#5]
All pages in my menu are affected including pages included by default.  Scroll bars are disabled and mouse wheel will not scroll the page.

**Comment by VA3HDL** [comment]
Scrolling has been fixed.

Cookies, bad news:
Since Chrome 85, a web page that's inside an iframe and that's on a different domain than the parent won't be able to read its own cookies, unless they've explicitly been set using SameSite=None and Secure.

**Comment by lscalpati** [comment]
Thanks!

**Comment by lscalpati** [comment]
Works great - thanks
