### ISSUE TITLE
Font issue in full screen

### ISSUE THREAD

**Issue by Sanman9781** [VA3HDL/hamdashboard#6]
On my widescreen monitor, when viewed in full-screen mode I see parts of the link labels due to oversized fonts. This is only an issue on the left side link buttons, not the right.
![chrome_BwErhqhWC7](https://github.com/VA3HDL/hamdashboard/assets/47226155/38967cd7-b415-4564-83c9-626e7132bb72)
![chrome_fW78vHSQ1h](https://github.com/VA3HDL/hamdashboard/assets/47226155/ef768859-650f-46d1-a78a-6020bdbc4d9f)

**Comment by VA3HDL** [comment]
Are you running the latest version of the browser? I believe someone else was telling me about a similar issue and he was running a old version of Chrome. He told the issue was fixed when he updated the browser to its latest version.
Could you please check that and let me know?

**Comment by VA3HDL** [comment]
Do you have a 4k monitor? I was able to reproduce the issue extending my browser across two HD screens. Will fix and let you know once is done.

**Comment by VA3HDL** [comment]
I made some changes on hamdash.html
to ensure the menu adapts its size to large resolution screens
please download the updated version and let me know if the issue persists. 

Thanks.
