### ISSUE TITLE
Install on Chrome OS

### ISSUE THREAD

**Issue by ckuter33** [VA3HDL/hamdashboard#7]
Cannot install on Chrome OS laptop.  Firefox not listed as option when I righr-clicked on the html file.  JS was installed.  Can only use Brave Browser when I right click on the .html file.  Top row of the dashboard pops up and nothing else.  Any ideas?  N9KO

**Comment by VA3HDL** [comment]
Any modern browser should work fine including Brave.
Download the HTML and the two .JS files on the SAME folder.
Without making any changes on the files yet, right click and open the HTML file only with the browser.
If this works, then proceed to customize to your preferences.
Please let me know how it goes.

**Comment by VA3HDL** [comment]
Calvin, if it still doesn't work then please press F12 to open the developer tools screen, click on "Console" and send me any errors showing there. Thanks.

**Comment by ckuter33** [comment]
My Chrome laptop has 10 F keys, but nowhere can I find what each key relates to.  Pressing each key does nothing.  Thanks for your suggestions.  Maybe soneone better than me can provide this data.  I use ASUS C523N running 124 64-bit build.

**Comment by VA3HDL** [comment]
I do not have any Chromebook available to me to check. I will leave this issue open until someone can check in a Chromebook.

**Comment by ckuter33** [comment]
Thanks for your comments.  I have your Dashboard working fine on W10 and Ubuntu. 

    On Monday, June 3, 2024 at 02:25:14 PM CDT, Pablo ***@***.***> wrote:  
 
 


I do not have any Chromebook available to me to check. I will leave this issue open until someone can check in a Chromebook.
